import java.util.Random;
public class NewApplet extends java.applet.Applet {

    /**
     * Initializes the applet NewApplet
     */
    static String comp="";
    static String player="";
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    public void play()
    {
        Random r = new Random();
		int input = r.nextInt(3);
		if(input==0)
		{
			comp="rock";
                        label5.setText("Computer choose : Rock");
		}
		else if(input==1)
		{
			comp="paper";
                        label5.setText("Computer choose : Paper");
		}
		else if(input==2)
		{
			comp="scissor";
                        label5.setText("Computer choose : Scissor");
		}
                result();
    }
    public void result()
    {
        if(player.equals(comp))
		{
			label6.setText("It's a Tie");
		}
		else if(comp.equals("rock"))

		{
			
                    if(player.equals("paper"))

			{
			
				label6.setText("Player Win.");
		
			}
			
			else if(player.equals("scissor"))
			{
				
				label6.setText("Computer Win.");

			}

		}

		else if(comp.equals("paper"))

		{
			
			if(player.equals("scissor"))

			{
	
				label6.setText("Player Win.");

			}

			else if(player.equals("rock"))

			{
	
				label6.setText("Computer Win.");

			}

		}

		else if(comp.equals("scissor"))

		{


			if(player.equals("rock"))

			{

				label6.setText("Player Win.");

			}

			else if(player.equals("paper"))
			{

				label6.setText("Computer Win.");

			}

		}	
    }
    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        label2 = new java.awt.Label();
        label1 = new java.awt.Label();
        panel3 = new java.awt.Panel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        panel5 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label3 = new java.awt.Label();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setLayout(null);

        label2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setName(""); // NOI18N
        label2.setText("Welcome to my game");
        panel2.add(label2);
        label2.setBounds(550, 10, 300, 30);

        add(panel2);
        panel2.setBounds(10, 10, 1350, 50);

        label1.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        label1.setText("Rock Paper Scissor");
        add(label1);
        label1.setBounds(580, 80, 270, 32);

        panel3.setBackground(new java.awt.Color(204, 204, 204));
        panel3.setLayout(null);

        button1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        button1.setLabel("Rock");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel3.add(button1);
        button1.setBounds(110, 20, 320, 40);

        button2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        button2.setLabel("Paper");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panel3.add(button2);
        button2.setBounds(510, 20, 340, 40);

        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        button3.setLabel("Scissor");
        button3.setMinimumSize(new java.awt.Dimension(57, 29));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panel3.add(button3);
        button3.setBounds(920, 20, 300, 40);

        add(panel3);
        panel3.setBounds(10, 120, 1350, 90);

        panel5.setBackground(new java.awt.Color(204, 204, 204));
        add(panel5);
        panel5.setBounds(790, 370, 200, 30);

        panel6.setBackground(new java.awt.Color(204, 204, 204));
        panel6.setLayout(null);

        label4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label4.setText("This is Player side");
        panel6.add(label4);
        label4.setBounds(130, 70, 370, 80);

        label5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label5.setText("This is Computer side");
        panel6.add(label5);
        label5.setBounds(930, 70, 410, 80);

        label6.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        label6.setText("Result Part");
        panel6.add(label6);
        label6.setBounds(530, 220, 520, 70);

        add(panel6);
        panel6.setBounds(10, 230, 1350, 350);

        label3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(153, 153, 153));
        label3.setText("Created by CJ");
        add(label3);
        label3.setBounds(1070, 600, 290, 49);
    }// </editor-fold>                        

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
         if(evt.getSource()==button3)
        {
            player = "scissor";
            label4.setText("Player choose : Scissor");
            play();
            repaint();
        }
    }                                       

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(evt.getSource()==button1)
        {
            player = "rock";
            label4.setText("Player choose : Rock");
            play();
            repaint();
        }
    }                                       

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
       
        if(evt.getSource()==button2)
        {
            player = "paper";
            label4.setText("Player choose : Paper");
            play();
            repaint();
        }
    }                                       


    // Variables declaration - do not modify                     
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    // End of variables declaration                   
}
/*
<applet code="NewApplet" width="700" height="700"></applet>
*/
